### PR TITLE
[feature] Create mobile navigation menu

### LINKED ISSUE #57: Create a Mobile UI for storybook
We don't need to support all of the features of Storybooks.
But some of the basic navigation and so on.

Also, we need to have a way to provide a way to go back to the default UI.

This shouldn't be a new CSS layout. But completely new UI.

### PR DESCRIPTION
**Pull request by fuller**
Creates a mobile navigation that can be used for filtering and choosing components from the component list. This is accomplished by creating Mobile and Desktop layout components that are rendered based on current media query. There are some additional optimizations we can make, but I tried to keep consistency with the current design and how styles are defined.

image

This PR also resolves some outstanding accessibility issues by adding an `href` to the navigation anchor tags. Without an `href` the link won't be focusable so you could not tab through the list.

Resolves #57 

I'm open to changing any parts of this so please let me know 😸

### CODE REVIEW

**Comment by ajfuller** [comment]
@ndelangen If you have some time, would love to get this in or modified to your standards. Thanks!

**Comment by ndelangen** [comment]
Thank you so much for this PR, I can see quite a few improvements! ❤️ 

I'll have a look asap.

**Comment by ajfuller** [comment]
@UsulPro have you had a chance to take a look yet? Please let me know if I can help explain any of my thought process.

**Comment by UsulPro** [comment]
@ajfuller I'll try to review it asap!

I think it could help us if we can test it on mobile device too.

At this moment I noticed an erorr in console when manually changing the screen resolution, but unfortunately I didn't have time to look into this more

**Comment by ajfuller** [comment]
I'll try to take a look at that and update the conflicting files, thanks!

**Comment by UsulPro** [comment]
@ajfuller would it be difficult if I ask you to deploy you PR to ghpages?

**Comment by UsulPro** [comment]
could you a bit explain why do you think we don't need to show DownPanel in mobile layout?

**Comment by ndelangen** [comment]
Hey @ajfuller  

Thank you so much for this PR! We're moving over to a mono-repo, since that makes a lot of sense for a project like this.
We would ❤️ it if you could create a PR here: https://github.com/storybooks/storybook

That'd be awesome, thanks!

**Comment by ajfuller** [comment]
@UsulPro sorry for delayed response this week was hectic
@ndelangen I'll get a PR opened against the monorepo today, including a test deployment to GH pages and re-including the DownPanel

**Comment by ndelangen** [comment]
That's super!! @ajfuller ❤️

**Pull request closed without merging**
